### ISSUE TITLE
Auth Token

### ISSUE THREAD

**Issue by Desperationis** [SuperSonicHub1/spotify2yt#1]
Based project but spotify auth token is out in the open, just wanted to let you know.

**Comment by SuperSonicHub1** [comment]
Oh, that isn't my auth token; it's Spotify's. ;) They leave it their HTML. At https://open.spotify.com/
```html
<script id="session" data-testid="session" type="application/json">
{"accessToken":"BQAv0CsKKJ3FyRGQFlAYVFMcQWV8_jfiDGxSkacn8T5anexYRToIA3iIv-srPEWd13i30m8ptLtCkJON8fPtSNqrPrU-C_OsgzIioefeXBOWHI3bfb5n","accessTokenExpirationTimestampMs":1677985454812,"isAnonymous":true,"clientId":"d8a5ed958d274c2e8ee717e6a4b0971d"}
</script>
```
Imagine actually bothering to get an API key; couldn't be me.

**Comment by SuperSonicHub1** [comment]
Oh wait, I am leaking.

**Comment by Desperationis** [comment]
lol

**Comment by SuperSonicHub1** [comment]
Thanks for the catch, brother. It luckily wasn't a big deal since the token already expired, but it still shouldn't be in there. Thank God for `git rebase`.
